font_family           JetBrainsMono Nerd Font
bold_font             JetBrainsMono Nerd Font Bold
italic_font           JetBrainsMono Nerd Font Italic
bold_italic_font      JetBrainsMono Nerd Font SemiBoldItalic
font_size             12.0
background_opacity    0.65
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell     no

window_padding_width  8
window_padding_height 8

cursor                #5dade2
cursor_text_color     background

url_color             #cce7e0

visual_bell_color     #65827e
bell_border_color     #65827e

active_border_color   #cce7e0
inactive_border_color #95a5a6

foreground            #cce7e0
background            #0e2537
selection_foreground  #cce7e0
selection_background  #2b4856

active_tab_foreground   #cce7e0
active_tab_background    #183142
inactive_tab_foreground  #cce7e0
inactive_tab_background  #2b4856

color0   #000000  
color8   #65827e  

color1   #e74c3c  
color9   #ff7675  

color2   #2ecc71  
color10  #58d68d  

color3   #f1c40f  
color11  #f4d03f  

color4   #3498db  
color12  #5dade2  

color5   #9b59b6  
color13  #af7ac5  

color6   #1abc9c  
color14  #48c9b0  

color7   #cce7e0  
color15  #2b4856  
