format = """
$os$username$directory$git_branch$git_status$c$elixir$elm$golang$gradle$haskell$java$julia$nodejs$nim$python$rust$scala$docker_context$time
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[❯](bold #5dade2) "
error_symbol = "[❯](bold #e74c3c) "

[username]
show_always = false
style_user = "bold #7eb1dd"
style_root = "bold #e74c3c"
format = "[$user]($style) "

[os]
disabled = false
style = "bold #5dade2"
format = "[$symbol]($style) "

[os.symbols]
Arch = "󰣇 "
Linux = "🐧 "

[directory]
style = "bold #7eb1dd"
format = "[$path]($style) "
truncation_length = 4
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = " "
style = "bold #94a3b8"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold #ff6b6b"
format = "[($all_status$ahead_behind)]($style) "

[c]
symbol = " "
style = "bold #64748b"
format = "[$symbol($version)]($style) "

[rust]
symbol = " "
style = "bold #64748b"
format = "[$symbol($version)]($style) "

[nodejs]
symbol = " "
style = "bold #64748b"
format = "[$symbol($version)]($style) "

[golang]
symbol = " "
style = "bold #64748b"
format = "[$symbol($version)]($style) "

[python]
symbol = "🐍 "
style = "bold #64748b"
format = "[$symbol($version )(\\($virtualenv\\) )]($style)"


[time]
disabled = false
time_format = "%R"
style = "bold #64748b"
format = "at [$time]($style)"